services:

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hamidjon4424
      POSTGRES_DB: restaurant
      PG_DATA: /var/lib/postgresql/data 
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - restaurant

  migrate:
    image: migrate/migrate
    networks:
      - restaurant
    volumes:
      - ./migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://postgres:hamidjon4424@postgres:5432/restaurant?sslmode=disable", "up"]
    depends_on:
      - postgres

  user-service:
    build: .
    container_name: user-service
    ports:
      - "7777:7777"
    environment:
      DATABASE_URL: "postgres://postgres:hamidjon4424@postgres:5432/restaurant?sslmode=disable"  # To'g'ri ulanish URL'si
    depends_on:
      - postgres
    networks:
      - restaurant

volumes:
  postgres-data:

networks:
  restaurant:
    external: true
